// <auto-generated />
using System;
using Dberries.Store.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dberries.Store.Persistence.Migrations
{
    [DbContext(typeof(MsSqlDbContext))]
    [Migration("20231027142149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dberries.Store.Item", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.ToTable("Items", "Item");
                });

            modelBuilder.Entity("Dberries.Store.Location", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .IsDescending()
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.ToTable("Locations", "Location");
                });

            modelBuilder.Entity("Dberries.Store.Item", b =>
                {
                    b.OwnsMany("Dberries.Store.Rating", "Ratings", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte?>("Value")
                                .IsRequired()
                                .HasColumnType("tinyint");

                            b1.HasKey("ItemId", "UserId");

                            b1.ToTable("Rating", "Item");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Dberries.Store.Location", b =>
                {
                    b.OwnsMany("Dberries.Store.Stock", "Stock", b1 =>
                        {
                            b1.Property<Guid>("LocationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Quantity")
                                .IsRequired()
                                .HasColumnType("int");

                            b1.HasKey("LocationId", "ItemId");

                            b1.HasIndex("ItemId");

                            b1.ToTable("Stock", "Location");

                            b1.HasOne("Dberries.Store.Item", "Item")
                                .WithMany()
                                .HasForeignKey("ItemId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("LocationId");

                            b1.Navigation("Item");
                        });

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
