version: '3.9'
name: domesticberries-elasticsearch

services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.12'
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=es-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - './elasticsearch-data:/usr/share/elasticsearch/data'
    networks:
      - domesticberries
    healthcheck:
      interval: 20s
      retries: 10
      test: >-
        curl -s http://localhost:9200/_cluster/health | grep -vq
        '"status":"red"'

networks:
  domesticberries:
    name: domesticberries
    external: true
