version: '3.9'

services:
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.12
    depends_on:
      es-tracing:
        condition: service_healthy
      kibana:
        condition: service_healthy
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
      - "8200:8200"
    networks:
      - domesticberries
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["es-tracing:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
    restart: unless-stopped
  
  es-tracing:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - './es-tracing-data:/usr/share/elasticsearch/data'
    ports:
      - "9200:9200"
    networks:
      - domesticberries
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    restart: unless-stopped
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.12
    depends_on:
      es-tracing:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_URL=http://es-tracing:9200
      - ELASTICSEARCH_HOSTS=http://es-tracing:9200
      - SERVER_BASEPATH=/kibana
    ports:
      - "5601:5601"
    networks:
      - domesticberries
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
    restart: unless-stopped

networks:
  domesticberries:
    name: domesticberries
    external: true